In [ ]:
#importing libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
#For unzipping dataset from google drive
# !unrar x "/content/drive/MyDrive/review_polarity.rar" "/content/drive/My Drive/"

In [ ]:
#processing data on "neg" folder and cleaning the data with scikit learn inbuilt libraries

import glob
txt_files = glob.glob("/content/drive/MyDrive/review_polarity/txt_sentoken/neg/*.txt")

corpus = []
corpus2 =[]
booleans = []

for i in range(len(txt_files)):
  booleans.append(0)

  with open(txt_files[i], 'r') as file:
    data = file.read().replace('\n', '')
    review = re.sub('[^a-zA-Z]', ' ', data)
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)
    helper =  nltk.WordPunctTokenizer().tokenize(review)
    corpus2.append(helper)
   

In [ ]:
#processing data on "pos" folder and cleaning the data with scikit learn inbuilt libraries

import glob
txt_files = glob.glob("/content/drive/MyDrive/review_polarity/txt_sentoken/pos/*.txt")
  


for i in range(len(txt_files)):
  booleans.append(1)
  with open(txt_files[i], 'r') as file:
    data = file.read().replace('\n', '')
    review = re.sub('[^a-zA-Z]', ' ', data)
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)
    helper =  nltk.WordPunctTokenizer().tokenize(review)
    corpus2.append(helper)
    # print(helper)
   
   

In [ ]:
print(len(booleans))
print(len(corpus2))

2000
2000


#Tokeinizing words

In [ ]:
#tokeninzing the words ( Building bag of words model )

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(  max_features=1400)
X = cv.fit_transform(corpus).toarray()

print(len(X[0]))
print(len(booleans))
print(len(X))


1400
2000
2000


In [ ]:
# Generating test and train data set 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, booleans, test_size = 0.20, random_state = 0)# Generating test and train data set 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, booleans, test_size = 0.20, random_state = 0)

#Naive Bayes 

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy of model :" ,accuracy_score(y_test, y_pred))

[[156  44]
 [ 69 131]]
accuracy of model : 0.7175


In [ ]:
for i in X_train[3]:
  print(i , end =" ")
print(len(X_train[2]) ,end=" ")

0 0 0 0 1 0 0 0 0 1 0 2 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 9 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 3 2 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 

#SVM

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
print(len(X_train) , len(y_train))

1600 1600


In [ ]:
y_pred1 = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
print("accuracy of model :" , np.around(accuracy_score(y_test, y_pred1)*100))

[[161  39]
 [ 32 168]]
accuracy of model : 82.0


#Max Entropy Classifer

In [ ]:
from sklearn import linear_model
#(X, y) = (features matrix, labels)
maxent = linear_model.LogisticRegression(penalty='l2', C=0.1)
maxent.fit(X_train, y_train)

y_predicted = maxent.predict(X_test)

print("accuracy of model :" ,np.around(accuracy_score(y_test, y_predicted)*100))

accuracy of model : 84.0


#Implementing on bi-grams

In [ ]:
#creating  a tokenizer model

from sklearn.feature_extraction.text import CountVectorizer

bow_converter = CountVectorizer(tokenizer=lambda doc: doc, lowercase=False)
x = bow_converter.fit_transform(corpus2)

words = bow_converter.get_feature_names()
len(words)

25297

In [ ]:
#Generating test and train data

from sklearn.model_selection import train_test_split
training_data, test_data , y_train1 , y_test1 = train_test_split(corpus2 , booleans, train_size = 0.25, random_state=1)

In [ ]:
# building a bigram 

bow_transform = CountVectorizer(tokenizer=lambda doc: doc, ngram_range=[2,2], lowercase=False , max_features=350000)

X_tr_bow = bow_transform.fit_transform(training_data)
X_te_bow = bow_transform.transform(test_data).toarray()

bigrams = bow_transform.get_feature_names()

X_tr_bow  = X_tr_bow.toarray()


y_tr = y_train1
y_te = y_test1
print(bigrams[-10 :])

# print(len(y_tr))
# print(X_tr_bow[1])

['zuko sandi', 'zundel face', 'zundel speak', 'zwick co', 'zwick deserv', 'zwick screenwrit', 'zwick sieg', 'zwigoff brilliant', 'zyci master', 'zyci za']


In [ ]:
#Gaussian model 


from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB( )

classifier.fit(X_tr_bow, y_tr)
y_pred = classifier.predict(X_te_bow)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_te, y_pred)
print(cm)
print("accuracy :" ,round(accuracy_score(y_te, y_pred)*100))


#Bigram model gave a low accurac compared to

[[508 254]
 [203 535]]
accuracy : 70


In [ ]:
print(len(X_train))
print(len(y_train))

1600
1600


#Logisitic Regression from scratch

In [ ]:
#Sigmod function 

def sigmoid(input):    
    output = 1 / (1 + np.exp(-input))
    return output

In [ ]:
# Creating weights and bias variables

init_parameters = {} 
init_parameters["weight"] = np.zeros(X_train.shape[1])
init_parameters["bias"] = 0
print(init_parameters)

{'weight': array([0., 0., 0., ..., 0., 0., 0.]), 'bias': 0}


In [ ]:
# Optimization function 

def optimize(X, Y,learning_rate,iterations,parameters): 
    size = X.shape[0]
  
    weight = parameters["weight"] 
   
    bias = parameters["bias"]

    for i in range(iterations): 
        sigma = sigmoid(np.dot(X, weight) + bias)
      
        loss = -1/size * np.sum(Y * np.log(sigma)) + (np.ones(len(Y)) - Y) * np.log(1-sigma)

      
        dW = 1/size * np.dot(X.T, (sigma - Y))
        db = 1/size * np.sum(sigma - Y)
        weight -= learning_rate * dW
        bias -= learning_rate * db 
    
    parameters["weight"] = weight
    parameters["bias"] = bias
    return parameters

In [ ]:
# Building model

def train(X, Y, learning_rate,iterations):
    print(len(X))
    print(len(Y))
    parameters_out = optimize(X, Y, learning_rate, iterations ,init_parameters)
    return parameters_out

In [ ]:

parameters_out = train(X_train, y_train, learning_rate = 0.02, iterations = 500)
parameters_out

1600
1600


{'bias': -0.1362041367079207,
 'weight': array([-0.07649132,  0.10273034,  0.02794866, ...,  0.00074313,
        -0.00358161, -0.00405264])}

In [ ]:

#predicition of test set data values

output_values = np.dot(X_test, parameters_out["weight"]) + parameters_out["bias"]


predictions = sigmoid(output_values) >= 1/2
predictions
print("Accuracy" , np.around(accuracy_score(y_test , predictions)*100))

Accuracy 84.0
